map $http_x_forwarded_proto $forwarded_proto {
  default $http_x_forwarded_proto;
  '' $scheme;
}

server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 6m;

  location /auth/ {
    proxy_pass http://content-server:8788;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
    proxy_set_header X-Forwarded-For $http_x_forwarded_for;
  }

  location /admin/ {
    proxy_pass http://content-server:8788;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
    proxy_set_header X-Forwarded-For $http_x_forwarded_for;
    proxy_request_buffering off;
  }

  location /content-assets/ {
    proxy_pass http://content-server:8788;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location ~* \.(?:js|css)$ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }
}
